version: '3'
services:
  prometheus:
    image: prom/prometheus:latest

    command:
      - --storage.tsdb.retention.time=7d
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - /var/lib/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - main
      
  grafana:
    image: grafana/grafana:latest

    ports:
      - "3000:3000"

    volumes:
      - grafana-storage:/var/lib/grafana

    networks:
      - main

  node_exporter_1:
    image: prom/node-exporter:latest

    ports:
      - "9100:9100"
    networks:
      - main
      
  node_exporter_2: 
    image: prom/node-exporter:latest
    ports:
      - "9101:9100"
    networks:
      - main
  
  uptime-kuma:
    image: louislam/uptime-kuma:1

    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    networks:
      - main


volumes: 
  grafana-storage:
  uptime-kuma-data:
  
networks:
  main:
    external: true
