version: '3.8'
services:
  database:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - main


volumes:
  dbdata6:

networks:
  main:
    external: true