version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: ["server", "--console-address", ":9001", "/data"]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

      # Важно: укажи публичные URL (особенно если есть nginx/https)
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}

      # Опционально: регион/стандартные теги
      MINIO_REGION_NAME: ${MINIO_REGION_NAME:-us-east-1}

      # Опционально: наблюдаемость
      # MINIO_PROMETHEUS_AUTH_TYPE: public
      # Если оставишь public — метрики без auth (удобно, но лучше закрыть сетью/фаерволом)

    volumes:
      - minio_data:/data

    networks:
      - backend

    ports:
      # API
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
      # Console
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
      rollback_config:
        order: stop-first
      resources:
        reservations:
          cpus: "0.25"
          memory: 256M
        limits:
          cpus: "1.0"
          memory: 2G

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  minio_data:

networks:
  backend:
    driver: overlay
    attachable: true
