version: "3.7"

services:
  psql:
    image: postgres:13
    command:
      - postgres
      - -c
      - shared_buffers=256MB
      - -c
      - max_connections=300
    shm_size: "800MB"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "traefik.enable=false"
    ports:
      - "5432:5432"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - main

configs:
  pg_hba.conf:
    external: true

networks:
  main:
    external: true

volumes:
  postgres_data:
    external: true

