version: "3.8"

networks:
  backend:
    external: true
    name: backend


volumes:
  pg18_data:
    driver: local
  pg18_backups:
    driver: local

secrets:
  pg_pass_postgres:
    external: true

configs:
  postgres_conf:
    file: ./postgresql.conf
  pg_hba_conf:
    file: ./pg_hba.conf
services:
  postgres:
    image: postgres:18
    secrets:
      - pg_pass_postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pass_postgres

      # важно для PG18: используем понятный путь
      PGDATA: /var/lib/postgresql/data
      TZ: "UTC"

    networks:
      - backend


    volumes:
      # в PG18 монтируем корень /var/lib/postgresql
      - pg18_data:/var/lib/postgresql
      - pg18_backups:/backups


    configs:
      - source: postgres_conf
        target: /etc/postgresql/postgresql.conf
        mode: 0444
      - source: pg_hba_conf
        target: /etc/postgresql/pg_hba.conf
        mode: 0444

    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 20s

    deploy:
      mode: replicated
      replicas: 1

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s

      update_config:
        order: stop-first
        parallelism: 1
        delay: 5s

      rollback_config:
        order: stop-first

      resources:
        reservations:
          cpus: "0.5"
          memory: 512M
        limits:
          cpus: "2.0"
          memory: 4G

      placement:
        constraints:
          - node.labels.pg == true

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
