version: "3.7"

services:
  redis:
    image: redis:alpine
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      TZ: "Asia/Almaty"
    ports:
      - "6379:6379"
    volumes:
      - data:/data
    networks:
      - main

networks:
  main:
    external: true

volumes:
  data: